GET http://localhost:3000/parkinglot

################################

GET http://localhost:3000/parkinglot/60414a1dfd6c312ffdfb7e58

################################
POST http://localhost:3000/parkinglot
Content-Type: application/json

{
    "carNumber": "AA-01-A-111",
    "slotNumber": "1",
    "parkinglot": "Ground Floor"
}

################################
DELETE http://localhost:3000/parkinglot/60414ff763468a31c38cbb1d